name: Push To Server And Rebuild
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ~/htdocs/
            git clone https://github.com/Valor-Intel/DataSearchEngine
            cd ~/htdocs/DataSearchEngine
            git pull origin main
            docker-compose down
            docker-compose up -d --build
