name: Push To Server And Rebuild
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@latest

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ~/htdocs/search.vuln.lol/DataSearchEngine
            git pull origin main
            docker-compose down
            docker-compose up -d --build